### ISSUE TITLE
Stylelint 14 support

### ISSUE THREAD

**Issue by scott-lc** [csstools/stylelint-prefer-nesting#11]
Stylelint 14 is out - https://stylelint.io/migration-guide/to-14

From a plugin standpoint, it looks like the upgrade to PostCSS 8 is the biggest internal change - https://stylelint.io/migration-guide/to-14/#plugin-authors

Is supporting Stylelint 14 as simple as changing the `engines` and  `peerDependencies` to..

```
  "engines": {
    "node": "^12.20.0 || ^14.13.1 || >=16.0.0"
  },

  "peerDependencies": {
    "stylelint": "10 - 14"
  },
```

?

**Comment by benbender** [comment]
I've opened https://github.com/csstools/stylelint-use-nesting/pull/12 to push a tiny little bit :D

**Comment by benbender** [comment]
@jonathantneal Hey, sorry for being annoying, but would it be possible to merge #12 so this can be used again? Would be very much appreciated!

**Comment by romainmenke** [comment]
It's been a while and we are now at Stylelint 16.
This is large change so the minimum version is now also Stylelint 16
