### ISSUE TITLE
Exclude media queries from linting

### ISSUE THREAD

**Issue by SimonEggert** [csstools/stylelint-prefer-nesting#13]
Thanks for the great plugin! Is it possible to exclude media queries from linting inside the `except` option?

I'm trying to achieve something like this:

### before
```
.foo {
  …
}

/* this must be nested */
.foo::before {
  …
}

/* this is ignored */
@media {
  .foo {
    …
  }
}
```

### after
```
.foo {
  …

  &::before {
    …
  }
}

@media {
  .foo {
    …
  }
}
```

Neither of the variants I tried are working.
```js
  rules: {
    'liberty/use-logical-spec': 'always',
    'csstools/use-nesting': [
      'always',
      {
        except: [
          '@media',
          /^@media/i,
          /.*@media.*/i,
        ],
      },
    ],
  },
```

Am I missing something?

**Comment by lucasdinonolte** [comment]
I'm having the exact same issue. Did you ever find a solution for this?

**Comment by romainmenke** [comment]
This plugin is already very complex.
Adding more config would make it even less maintainable.

I won't add this at this time.
