### ISSUE TITLE
Remove @nest?

### ISSUE THREAD

**Issue by osmestad** [csstools/stylelint-prefer-nesting#15]
Hi,

As `@nest` has been removed from the latest specification(https://www.w3.org/TR/css-nesting-1/), I think it would make sense to remove it here as well? 
(It will soon give a warning in the PostCSS plugin: https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-nesting#%EF%B8%8F-nest-has-been-removed-from-the-specification)

Maybe it could be achieved by just switching to the SCSS syntax added in https://github.com/csstools/stylelint-use-nesting/pull/14 as default?

**Comment by romainmenke** [comment]
This was released as part of `5.1.0`
