### ISSUE TITLE
Stylelint could not find "stylelint-use-nesting"

### ISSUE THREAD

**Issue by tomekpiwowar** [csstools/stylelint-prefer-nesting#18]
I've installed the latest version of plugin (5.1.0), expecting it to solve the problem described in this PR https://github.com/csstools/stylelint-use-nesting/pull/17 , however now I got an error after running `yarn stylelint`:

`Error: Could not find "stylelint-use-nesting". Do you need to install the package or use the "configBasedir" option?`

**Comment by romainmenke** [comment]
Maybe because the rule name is `csstools/use-nesting`?

https://github.com/csstools/stylelint-use-nesting/blame/49b77d11bb466eebd94fad1d4e31dc1ad988eeb3/src/index.js#L10


Can you share your config?

**Comment by tomekpiwowar** [comment]
My .stylelintrc.json:
```json
{
  "extends": [
    "stylelint-config-standard",
    "stylelint-prettier/recommended"
  ],
  "plugins": [
    "stylelint-declaration-strict-value",
    "stylelint-value-no-unknown-custom-properties",
    "stylelint-media-use-custom-media",
    "stylelint-use-nesting",
    "stylelint-order",
  ],
  "rules": {
    {some rules...}
    "csstools/media-use-custom-media": "always",
    "csstools/use-nesting": "always",
    {some rules...}
  }
}
```

I don't think it's about the rule name because as you can see _stylelint-media-use-custom-media_ and its rule _csstools/media-use-custom-media_ has same naming convention and it's working well.

I found that the error disappears and plugin starts working after refactoring "exports" in the plugin package.json from this:
```
"exports": {
    ".": {
      "import": "./index.mjs"
    }
  },
```
to this:
` "exports": "./index.mjs",`

I think the exports might be unnecessarily conditional because:
- it might enforce the ES Modules support in whole project (which I think is the reason of the error in my case), but it doesn't has to
- the plugin and the stylelint 16+ itself supports ES Modules only anyway.

**Comment by romainmenke** [comment]
Good catch!

I'll fix that later today
Thank you

**Comment by romainmenke** [comment]
@tomekpiwowar I've completely remove the exports field.
This also seems to work if I set up a fresh project:

<img width="539" alt="Screenshot 2024-03-06 at 17 46 50" src="https://github.com/csstools/stylelint-use-nesting/assets/11521496/8e59a772-1fce-4493-ab81-36e9e2685523">


Can you verify that everything is now fixed on your end?

**Comment by tomekpiwowar** [comment]
@romainmenke I just tested the package after your update and everything works properly. Thank You!
