### ISSUE TITLE
Is this plugin still in maintenance?

### ISSUE THREAD

**Issue by jens-duttke** [csstools/stylelint-prefer-nesting#6]
It's relying on an outdated stylelint version.
A user provided a fix before 2 months (#5 ), but there is no reaction from a maintainer.

The CHANGELOG.md references a version 2.0.0, dated May 12, 2018 - but it was never released on NPM.

**Comment by sobolevn** [comment]
Thanks a lot for the merge of #5! I would appreciate a new release.

**Comment by jonathantneal** [comment]
I am awaiting the results of https://travis-ci.org/csstools/stylelint-use-nesting/builds/645417899

**Comment by jonathantneal** [comment]
Thank you, @sobolevn, for the fix. Thank you, @jens-duttke, for the reminder.

2.0.0 is released.
